services:
  - type: web
    name: egov-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: egov-db
          property: connectionString
databases:
  - name: egov-db
    plan: free
